---
- hosts: all
  become: yes
  tasks:
    - name: Add Docker GPG key
      apt_key: 
        url: https://download.docker.com/linux/ubuntu/gpg
    - name: Install basic list of packages
      apt:
        name: ['apt-transport-https','ca-certificates','curl','gnupg2','software-properties-common']
        state: present
        update_cache: yes
    - name: Add Docker APT repository
      apt_repository:
          repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable
    - name: Install Docker packages
      apt:
#        name: "{{ item }}" 
        name: ['docker-ce','docker-ce-cli', 'containerd.io']
        state: present
#      with_items:
#            - docker-ce={{ dockerceversion }}
#            - docker-ce-cli={{ dockercecliversion }}
#            - containerd.io={{ containerdioversion }}
#            - docker-ce
#            - docker-ce-cli
#            - containerd.io
